# Bonfire deployment configuration

# Defines where to fetch the file that defines application configs
appsFile:
  host: gitlab
  repo: insights-platform/cicd-common
  path: bonfire_configs/ephemeral_apps.yaml

# (optional) define any apps locally. An app defined here with <name> will override config for app
# <name> in above fetched config.
envName: env-metaverse
apps:
- name: rbac
  components:
  - name: rbac
    host: local
    repo: /home/bholifie/git/insights-rbac/
    path: deploy/rbac-clowdapp.yml
    parameters:
      # IMAGE: 192.168.39.77:5000/host-inventory
      IMAGE: 127.0.0.1:5000/rbac
      CLOWDER_ENABLED: "true"
      PERMISSION_SEEDING_ENABLED: "false"
      ROLE_SEEDING_ENABLED: "false"
      GROUP_SEEDING_ENABLED: "false"
      DISABLE_MIGRATE: "false"
      EPH_ENV: "true"
